name: Keep Medilab Alive

on:
  schedule:
    # Run every 6 days at midnight UTC
    - cron: "0 0 */6 * *"

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Medilab
        run: curl -s -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" "https://${{secrets.MEDILAB_PROJECT_REF}}.supabase.co/rest/v1/Appointment?select=id" || echo "Ping failed"
